import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { Card } from "@/components/ui/card";
import { useEffect } from "react";

const Privacy = () => {
  useEffect(() => {
    document.title = "AI Flow | Privacy Policy";
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      <main className="container mx-auto px-6 pt-32 pb-20">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Privacy <span className="text-primary">Policy</span>
          </h1>
          <p className="text-muted-foreground mb-8">Last updated: December 18, 2021</p>

          <Card className="bg-card border-border p-8 md:p-12 space-y-8">
            <section>
              <p className="text-muted-foreground leading-relaxed">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-4">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-primary">Interpretation and Definitions</h2>
              
              <h3 className="text-xl font-semibold mb-3 mt-6">Interpretation</h3>
              <p className="text-muted-foreground leading-relaxed">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="text-xl font-semibold mb-3 mt-6">Definitions</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                For the purposes of this Privacy Policy:
              </p>
              <ul className="space-y-3 text-muted-foreground">
                <li><strong className="text-foreground">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong className="text-foreground">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AI FLOW SOFTWARE S.R.L., Cluj-Napoca, Romania, 400594.</li>
                <li><strong className="text-foreground">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong className="text-foreground">Country</strong> refers to: Romania.</li>
                <li><strong className="text-foreground">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong className="text-foreground">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong className="text-foreground">Service</strong> refers to the Website, aiflow.ltd and console.aiflow.ltd.</li>
                <li><strong className="text-foreground">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong className="text-foreground">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong className="text-foreground">Website</strong> refers to AI Flow, accessible from https://www.aiflow.ltd/</li>
                <li><strong className="text-foreground">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-primary">Collecting and Using Your Personal Data</h2>
              
              <h3 className="text-xl font-semibold mb-3 mt-6">Types of Data Collected</h3>
              
              <h4 className="text-lg font-semibold mb-2 mt-4">Personal Data</h4>
              <p className="text-muted-foreground leading-relaxed mb-2">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="text-lg font-semibold mb-2 mt-6">Usage Data</h4>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Usage Data is collected automatically when using the Service.
              </p>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Tracking Technologies and Cookies</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
              </p>
              <p className="text-muted-foreground leading-relaxed mb-4">
                We use both Session and Persistent Cookies for the purposes set out below:
              </p>
              <ul className="space-y-4 text-muted-foreground">
                <li>
                  <strong className="text-foreground">Necessary / Essential Cookies</strong><br />
                  Type: Session Cookies<br />
                  Administered by: Us<br />
                  Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.
                </li>
                <li>
                  <strong className="text-foreground">Cookies Policy / Notice Acceptance Cookies</strong><br />
                  Type: Persistent Cookies<br />
                  Administered by: Us<br />
                  Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                </li>
                <li>
                  <strong className="text-foreground">Functionality Cookies</strong><br />
                  Type: Persistent Cookies<br />
                  Administered by: Us<br />
                  Purpose: These Cookies allow us to remember choices You make when You use the Website.
                </li>
              </ul>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Use of Your Personal Data</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                The Company may use Personal Data for the following purposes:
              </p>
              <ul className="space-y-3 text-muted-foreground">
                <li><strong className="text-foreground">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                <li><strong className="text-foreground">To manage Your Account</strong>: to manage Your registration as a user of the Service.</li>
                <li><strong className="text-foreground">To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                <li><strong className="text-foreground">To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
                <li><strong className="text-foreground">To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
                <li><strong className="text-foreground">For business transfers</strong>: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              </ul>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Retention of Your Personal Data</h3>
              <p className="text-muted-foreground leading-relaxed">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Transfer of Your Personal Data</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Disclosure of Your Personal Data</h3>
              <h4 className="text-lg font-semibold mb-2 mt-4">Business Transactions</h4>
              <p className="text-muted-foreground leading-relaxed mb-4">
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </p>
              
              <h4 className="text-lg font-semibold mb-2 mt-4">Law Enforcement</h4>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.
              </p>

              <h4 className="text-lg font-semibold mb-2 mt-4">Other Legal Requirements</h4>
              <p className="text-muted-foreground leading-relaxed mb-2">
                The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Security of Your Personal Data</h3>
              <p className="text-muted-foreground leading-relaxed">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Children's Privacy</h3>
              <p className="text-muted-foreground leading-relaxed">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Links to Other Websites</h3>
              <p className="text-muted-foreground leading-relaxed">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold mb-3">Changes to this Privacy Policy</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-primary">Contact Us</h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <p className="text-muted-foreground leading-relaxed mt-2">
                By email: <a href="mailto:contact@aiflow.ltd" className="text-primary hover:underline">contact@aiflow.ltd</a>
              </p>
            </section>
          </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Privacy;

